import { type NextPage } from "next";
import Head from "next/head";
import SearchForm from "../components/searchForm";

const Search: NextPage = () => {
  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center justify-center">
          <SearchForm test="" />
        </div>
      </main>
    </>
  );
};

export default Search;
