import { type NextPage } from "next";
import Head from "next/head";

type SpacebattlesSearch = {
  keyWords?: string;
  tags?: string[];
  excludeTags?: string[];
  newerThan?: Date;
  olderThan?: Date;
  users?: string[];
  wordCountLower?: string;
  wordCountUpper?: string;
  replies?: string;
  order?: "date" | "relevance" | "words" | "last_update" | "replies";
};

const Search: NextPage = () => {
  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="flex flex-col items-center gap-2"></div>
        </div>
      </main>
    </>
  );
};

export default Search;
